"""
Django settings for ecobin_backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import environ
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Read the .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'phonenumber_field',
    'drf_spectacular',
    'accounts',
    'pickups',
    'users',
    'operators',
    'operator_admins',
    'superadmins',
    'payments',
    'complaints',
    'channels',
    'chat',
    'services',
    'waste',
]

AUTH_USER_MODEL = 'accounts.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecobin_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecobin_backend.wsgi.application'
ASGI_APPLICATION = 'ecobin_backend.asgi.application'

# Django Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [env('REDIS_URL', default='redis://localhost:6379/0')],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_RATES': {
        'waste_scan': '10/min',
    },
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



# Celery
CELERY_BROKER_URL = env('REDIS_URL')
CELERY_RESULT_BACKEND = env('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

# Redis as Django's cache backend (this is what stores the OTP)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Email backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env.int('EMAIL_PORT')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')


GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET')

# Razorpay
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET')

# Tracking simulation speed multiplier
# 60 = 1 real second = 1 simulated minute (5-min route takes ~5 seconds)
TRACKING_SPEED_MULTIPLIER = 60

# Waste Scanner (Groq)
GROQ_API_KEY = env('GROQ_API_KEY', default='')
GROQ_MODEL = env('GROQ_MODEL', default='qwen/qwen3.8-27b')
CONFIDENCE_THRESHOLD = env.int('CONFIDENCE_THRESHOLD', default=60)

SPECTACULAR_SETTINGS = {
    'TITLE': 'EcoBin API',
    'DESCRIPTION': 'EcoBin Waste Management Backend API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    'ENUM_NAME_OVERRIDES': {
        'PickupStatusEnum': 'pickups.models.PickupRequest.STATUS_CHOICES',
        'WasteCollectionStatusEnum': 'payments.models.WasteCollection.STATUS_CHOICES',
        'PaymentStatusEnum': 'payments.models.Payment.PAYMENT_STATUS_CHOICES',
        'TrackingStatusEnum': 'pickups.models.PickupTracking.STATUS_CHOICES',
        'ServiceRequestStatusEnum': 'services.models.ServiceRequest.STATUS_CHOICES',
    },
    'TAGS': [
        {'name': 'Public', 'description': 'Public endpoints — no authentication required (Register, Login, Password Reset, 2FA Login, Google Auth)'},
        {'name': 'User', 'description': 'User endpoints — requires User role (Onboarding, Account Info, Profile, Password Change, Logout)'},
        {'name': 'User - Reviews', 'description': 'User review endpoints — submit and view operator reviews for completed pickups'},
        {'name': 'User - Complaints', 'description': 'User complaint endpoints — create, list, and view complaints'},
        {'name': 'User - Payments', 'description': 'User payment status — view payment status for pickups'},
        {'name': 'Staff', 'description': 'Staff endpoints — requires Operator or OperatorAdmin role (Onboarding, Account Info, Profile, Password Change, Logout)'},
        {'name': 'Operators', 'description': 'Operator endpoints — requires Operator role (Onboarding, Account, Reviews, Location, Assigned Pickups, Collections, Payments, Complaints)'},
        {'name': 'Operator Admins', 'description': 'Operator Admin endpoints — requires OperatorAdmin role (Onboardings, Pickups, Complaints, Operator Ratings)'},
        {'name': 'Super Admins', 'description': 'SuperAdmin endpoints — requires SuperAdmin role (Users, Operators, OperatorAdmins, Onboardings, Ratings)'},
        {'name': 'Pickups', 'description': 'Pickup request endpoints — create and manage waste pickup requests'},
        {'name': 'Chat - Communities', 'description': 'Community group chat — create, list, update, deactivate communities'},
        {'name': 'Chat - Members', 'description': 'Community members — add, remove, list, update permissions'},
        {'name': 'Chat - Messages', 'description': 'Chat messages — paginated message history for communities'},
        {'name': 'Services', 'description': 'Service tracking endpoints — create, accept, reject, track service requests'},
        {'name': 'Complaints', 'description': 'Complaint management endpoints — create, list, assign, and resolve complaints'},
        {'name': 'Waste Scanner', 'description': 'AI waste classification — upload a photo and get plastic/e-waste/neither classification'},
    ],
}