# Generated by Django 6.1 on 2026-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0003_operatorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='place',
            field=models.CharField(blank=True, help_text='Text address — auto-converted to lat/lng via geocoding', max_length=500, null=True),
        ),
    ]
