# Generated by Django 6.1 on 2026-09-20 09:52

import django.db.models.deletion
import pickups.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0006_area_areaassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_id_display', models.CharField(help_text='Operator ID displayed on collection report', max_length=20)),
                ('resident_name', models.CharField(max_length=200)),
                ('resident_email', models.EmailField(blank=True, default='', max_length=254)),
                ('resident_phone', models.CharField(blank=True, default='', max_length=20)),
                ('house_address', models.TextField()),
                ('waste_type', models.CharField(choices=[('PLASTIC', 'Plastic'), ('E_WASTE', 'E-Waste'), ('ORGANIC', 'Organic'), ('PAPER', 'Paper'), ('GLASS', 'Glass'), ('METAL', 'Metal'), ('MIXED', 'Mixed')], max_length=20)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=8, null=True)),
                ('qr_code', models.CharField(default=pickups.models.generate_collection_qr_code, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('FAILED', 'Failed')], default='COLLECTED', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_collections', to='pickups.area')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_records', to=settings.AUTH_USER_MODEL)),
                ('pickup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_collections', to='pickups.pickuprequest')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
