# Generated by Django 6.1 on 2026-09-20 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0007_collectionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_place', models.CharField(blank=True, default='', max_length=500)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('route_data', models.JSONField(blank=True, default=dict)),
                ('total_distance_meters', models.FloatField(default=0)),
                ('total_duration_seconds', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='0.0 to 1.0 along route')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tracking', to=settings.AUTH_USER_MODEL)),
                ('pickup_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='pickups.pickuprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
