# Generated by Django 6.1 on 2026-09-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0008_pickuptracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuptracking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuptracking',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('COLLECTING', 'Collecting'), ('COMPLETED', 'Completed'), ('PAID', 'Paid')], default='NOT_STARTED', max_length=20),
        ),
    ]
