# Generated by Django 6.1 on 2026-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-created_at'], 'permissions': (('can_view_communities', 'Can list/view communities'), ('can_create_community', 'Can create a community'), ('can_manage_community', 'Can update/deactivate a community'), ('can_manage_members', 'Can add/remove members and change permissions'))},
        ),
    ]
