upstream backend {
    server 127.0.0.1:8000;
}

# HTTP Server - Redirects all traffic to HTTPS
server {
    listen 80;
    server_name ecobinproduction.duckdns.org 15.252.58.64 _;
    return 301 https://$host$request_uri;
}

# HTTPS Server - SSL Termination with Let's Encrypt
server {
    listen 443 ssl;
    server_name ecobinproduction.duckdns.org 15.252.58.64 _;
    client_max_body_size 6M;

    ssl_certificate /etc/letsencrypt/live/ecobinproduction.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ecobinproduction.duckdns.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
    }

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }

    location /ws/ {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
    }
}
