# Generated by Django 6.1 on 2026-09-09 21:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickups', '0002_pickuprequest_accepted_at_pickuprequest_accepted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plastic_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('e_waste_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('plastic_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8)),
                ('e_waste_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8)),
                ('plastic_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('e_waste_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online (Razorpay)')], default='CASH', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AMOUNT_DUE', 'Amount Due'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_collections', to=settings.AUTH_USER_MODEL)),
                ('pickup_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waste_collection', to='pickups.pickuprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online (Razorpay)')], max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Order Created'), ('CAPTURED', 'Captured (Paid)'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=256)),
                ('receipt', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.wastecollection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
