# Generated by Django 6.1 on 2026-09-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('pickups', '0009_pickuptracking_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollection',
            name='resident_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='resident_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='resident_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='scheduled_pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_collection', to='pickups.scheduledpickup'),
        ),
        migrations.AlterField(
            model_name='wastecollection',
            name='pickup_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_collection', to='pickups.pickuprequest'),
        ),
    ]
